// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAICdkv763_2Q3KFRIH4GorqRTMEm2XBGg',
    appId: '1:525966129684:android:f9667dbf7d740a055e8501',
    messagingSenderId: '525966129684',
    projectId: 'final-test-c79f5',
    storageBucket: 'final-test-c79f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfDNCp1y0jT0utHy2qqJO0fT_aJP6yEvw',
    appId: '1:525966129684:ios:8042f90c87e912575e8501',
    messagingSenderId: '525966129684',
    projectId: 'final-test-c79f5',
    storageBucket: 'final-test-c79f5.appspot.com',
    androidClientId: '525966129684-0v2vnbnmj3rmm4jl87j25iavsmda86vq.apps.googleusercontent.com',
    iosClientId: '525966129684-fj24fk53f8kf50aakjigetfaqv70st34.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFinalExam3',
  );
}
